export const FIELD_LABELS: Record<string, string> = {
  source_id: "原始ID",
  merchant_name: "商户名称",
  customer_source: "客户来源",
  delivery_date: "交付日期",
  referrer: "引荐人",
  customer_name: "客户名称",
  customer_phone: "客户电话",
  vin: "车架号",
  brand: "品牌",
  model_series: "车系",
  customer_type: "客户类型",
  fuel_type: "燃料类型",
  is_gifted: "是否赠送礼品",
  gift_name: "赠送礼品名称",
  salesperson: "销售员",
  create_method: "创建方式",
  creator_nick: "创建人昵称",
  create_time: "创建时间",
  updater_nick: "更新人昵称",
  update_time: "更新时间",
  contact_status: "触客情况",
  no_contact_reason: "未触客原因",
  no_contact_note: "未触客说明",
  referral_bonus_status: "引荐金发放状态",
  referral_bonus_amount: "引荐金发放金额",
  sales_recording: "销售录音",
  handover_doc: "交接单",
  gender: "性别",
  age_group: "年龄",
  payment_method: "购车付款方式",
  owner_type: "车主类型",
  usage_scenario: "用车场景",
  residence: "常住地",
  occupation: "职业",
  product_source: "产品来源",
  product_type: "产品类型",
  product_name: "产品名称",
  deal_status: "成交状态",
  is_store_product: "是否店端产品",
  deal_date: "成交日期",
  refund_date: "退款日期",
  refund_amount: "退款金额",
  product_years: "产品年限",
  deal_amount: "销售金额",
  related_order: "关联订单",
  no_deal_reason: "未成交原因",
  no_deal_note: "未成交说明",
  referral_bonus: "引荐金",
  is_given: "是否赠送",
  order_screenshot: "订单截图",
  order_screenshot_ocr: "订单截图OCR",
  rights_screenshot: "权益截图",
  rights_screenshot_ocr: "权益截图OCR",
  is_abnormal: "是否异常客户",
  abnormal_info: "异常信息",
};

export const FILTERABLE_FIELDS = [
  "brand", "model_series", "salesperson", "product_type", "product_source",
  "deal_status", "contact_status", "gender", "age_group", "customer_source",
  "merchant_name", "payment_method", "owner_type", "product_years", "fuel_type",
  "create_method", "referrer", "residence", "occupation", "customer_type",
  "is_store_product", "is_abnormal",
  "lingpao_region", "store_province", "store_city", "is_lingpao", "store_manager",
];

// Additional labels for store mapping fields
export const EXTRA_LABELS: Record<string, string> = {
  lingpao_region: "零跑大区",
  store_province: "省",
  store_city: "市",
  is_lingpao: "是否零跑",
  store_manager: "门店总经理",
};

export const FIELD_OPERATORS: Record<string, string[]> = {
  default: ["eq", "neq", "in", "nin"],
  text: ["eq", "neq", "in", "nin", "contains", "startswith"],
  number: ["eq", "neq", "in", "nin", "gte", "lte", "between"],
  date: ["eq", "neq", "between"],
};

export function getFieldLabel(field: string): string {
  return FIELD_LABELS[field] || EXTRA_LABELS[field] || field;
}
